//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RT.Servers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RT.Servers.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] bmp_16 {
            get {
                object obj = ResourceManager.GetObject("bmp_16", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] csv_16 {
            get {
                object obj = ResourceManager.GetObject("csv_16", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] doc_16 {
            get {
                object obj = ResourceManager.GetObject("doc_16", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] exe_16 {
            get {
                object obj = ResourceManager.GetObject("exe_16", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] faq_16 {
            get {
                object obj = ResourceManager.GetObject("faq_16", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] folder_16 {
            get {
                object obj = ResourceManager.GetObject("folder_16", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] folder_48 {
            get {
                object obj = ResourceManager.GetObject("folder_48", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] gz_16 {
            get {
                object obj = ResourceManager.GetObject("gz_16", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] jpg_16 {
            get {
                object obj = ResourceManager.GetObject("jpg_16", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] pdf_16 {
            get {
                object obj = ResourceManager.GetObject("pdf_16", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] pic_16 {
            get {
                object obj = ResourceManager.GetObject("pic_16", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] png_16 {
            get {
                object obj = ResourceManager.GetObject("png_16", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] pps_16 {
            get {
                object obj = ResourceManager.GetObject("pps_16", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ppt_16 {
            get {
                object obj = ResourceManager.GetObject("ppt_16", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] txt_16 {
            get {
                object obj = ResourceManager.GetObject("txt_16", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] xls_16 {
            get {
                object obj = ResourceManager.GetObject("xls_16", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] zip_16 {
            get {
                object obj = ResourceManager.GetObject("zip_16", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
